on: pull_request

jobs:
  find-flags:
    runs-on: ubuntu-latest
    name: Find LaunchDarkly feature flags in diff
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find flags
        uses: launchdarkly/find-code-references-in-pull-request@v1.1.0
        id: find-flags
        with:
          project-key: ${{ vars.LD_PROJECT }}
          environment-key: production
          access-token: ${{ secrets.LD_ACCESS_TOKEN_CR }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}